install.packages("rvest")
install.packages("httr")
install.packages("XML2R")
install.packages("tidytext")
install.packages("ggrepel")
library(rvest)
library(httr)
library(XML2R)

install.packages(c("rvest", "httr", "tidytext"))